create table GDM_WEB.ANALYSIS(
ANALYSIS_ID NUMBER(22,0) NOT NULL ,
ANALYSIS_VARIATION VARCHAR2(10),
ANALYSIS_TYPE_ID NUMBER(22,0),
LAB_TYPE_ID NUMBER(22,0),
COMMON_NAME_ID NUMBER(22,0),
REMOVED VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
METHOD VARCHAR2(50),
CONSTRAINT PK_ANALYSIS PRIMARY KEY (ANALYSIS_ID)
 );  
create table GDM_WEB.ANALYSIS_TRANS(
ANALYSIS_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
ANALYSIS_NAME VARCHAR2(50),
ANALYSIS_DESC VARCHAR2(300),
ANALYSIS_COMMENT VARCHAR2(300),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(30),
CONSTRAINT PK_ANALYSIS_TRANS PRIMARY KEY (ANALYSIS_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.ANALYSIS_TYPES(
ANALYSIS_TYPE_ID NUMBER(22,0),
LANGUAGE_ID NUMBER(22,0),
ANALYSIS_TYPE_DESC VARCHAR2(300),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(10) );  
create table GDM_WEB.AUDITS(
AUDIT_ID NUMBER(22,0) NOT NULL ,
SOURCE_AUDIT_NUM NUMBER(22,0) NOT NULL ,
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
MXNS_ENTITY_ID NUMBER(22,0),
CHECKLIST_ID NUMBER(22,0),
SOURCE_CHECKLIST_NUM NUMBER(22,0),
SOURCE_VARIATION_NUM NUMBER(22,0),
SOURCE_VERSION_NUM NUMBER(22,0),
SOURCE_ORDER_NUM NUMBER(22,0),
SOURCE_VISIT_NUM NUMBER(22,0),
SITE_ID NUMBER(22,0),
HIERARCHY_ID NUMBER(22,0),
CUSTOMER_ID NUMBER(22,0),
REPORT_ID NUMBER(22,0),
AP_REPORT_ID NUMBER(22,0),
AL_REPORT_ID NUMBER(22,0),
AUDIT_REPORT_NUM VARCHAR2(10),
SERVICE_CODE VARCHAR2(50),
SERVICE_DESC VARCHAR2(300),
STATUS_ID NUMBER(22,0),
SHIPVIA VARCHAR2(50),
PURCHASE_ORDER VARCHAR2(50),
AUDIT_START_DATE DATE
,
AUDIT_END_DATE DATE
,
VISIT_START_DATE DATE
,
VISIT_END_DATE DATE
,
EXPECTED_DATE DATE
,
SUBMIT_DATE DATE
,
REVIEWED_DATE DATE
,
ADDITIONAL_TITLE VARCHAR2(300),
SCORE VARCHAR2(50),
IN_SPEC VARCHAR2(1),
IN_ALERT VARCHAR2(1),
PERSON_MET VARCHAR2(60),
AUDIT_COMMENT VARCHAR2(1000),
IS_AGREEMENT_SENT VARCHAR2(1),
IS_AGREEMENT_SIGNED VARCHAR2(1),
AUDITOR_CODE VARCHAR2(10),
AUDITOR_FULL_NAME VARCHAR2(60),
ORDER_ID NUMBER(22,0),
SERVICE_ID NUMBER(22,0),
UPDATED_ON DATE
,
CONSTRAINT PK_AUDITS PRIMARY KEY (SOURCE_INSTANCE,SOURCE_AUDIT_NUM)
 );  
create table GDM_WEB.AUDIT_CATEGORY(
AUDIT_ID NUMBER(22,0) NOT NULL ,
CATEGORY_ID NUMBER(22,0) NOT NULL ,
UPDATED_ON DATE
,
CONSTRAINT PK_AUDIT_CATEGORY PRIMARY KEY (AUDIT_ID,CATEGORY_ID)
 );  
create table GDM_WEB.AUDIT_OPTION(
AUDIT_ID NUMBER(22,0) NOT NULL ,
OPTION_ID NUMBER(22,0) NOT NULL ,
UPDATED_ON DATE
,
CONSTRAINT PK_AUDIT_OPTION PRIMARY KEY (AUDIT_ID,OPTION_ID)
 );  
create table GDM_WEB.CATEGORY(
CATEGORY_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
CATEGORY_NAME VARCHAR2(50),
CATEGORY_DESC VARCHAR2(300),
CATEGORY_TYPE VARCHAR2(10),
PARENT_CATEGORY_ID NUMBER(22,0),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(10),
CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.CHECKLIST(
CHECKLIST_ID NUMBER(22,0) NOT NULL ,
SOURCE_CHECKLIST_NUM NUMBER(22,0) NOT NULL ,
SOURCE_VARIATION_NUM NUMBER(22,0) NOT NULL ,
SOURCE_VERSION_NUM NUMBER(22,0) NOT NULL ,
UPDATED_ON DATE
,
CONSTRAINT PK_CHECKLIST PRIMARY KEY (CHECKLIST_ID)
 );  
create table GDM_WEB.CHECKLIST_TRANS(
CHECKLIST_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
CHECKLIST_TITLE VARCHAR2(300),
VARIATION_TITLE VARCHAR2(300),
FOOT_NOTE VARCHAR2(300),
CONSTRAINT PK_CHECKLIST_TRANS PRIMARY KEY (CHECKLIST_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.CLIENT_MARKET(
CLIENT_MARKET_ID NUMBER(22,0) NOT NULL ,
CLIENT_MARKET_NAME VARCHAR2(20) NOT NULL ,
CLIENT_MARKET_DESC VARCHAR2(60),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(30) NOT NULL ,
CONSTRAINT PK_CLIENT_MARKET PRIMARY KEY (CLIENT_MARKET_ID)
 );  
create table GDM_WEB.COMMON_NAME(
COMMON_NAME_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
COMMON_NAME_DESC VARCHAR2(50),
REMOVED VARCHAR2(1),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(30),
CONSTRAINT PK_COMMON_NAME PRIMARY KEY (COMMON_NAME_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.CONCL_WEIGHT(
CONCL_WEIGHT_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
CONCL_WEIGHT NUMBER(22,0),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(30),
CONSTRAINT PK_CONCL_WEIGHT PRIMARY KEY (CONCL_WEIGHT_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.CUSTOMER(
CUSTOMER_ID NUMBER(22,0) NOT NULL ,
CUSTOMER_DESC VARCHAR2(300),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
TS_PERSON VARCHAR2(10),
CS_PERSON VARCHAR2(10),
CLIENT_MARKET_ID NUMBER(22,0),
MAX_DAYS_DATA_RETAINED NUMBER(22,0),
IS_GKA VARCHAR2(1) DEFAULT 'F'
   ,
CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
 );  
create table GDM_WEB.CUSTOMER_HIERARCHY(
CUSTOMER_ID NUMBER(22,0) NOT NULL ,
HIERARCHY_ID NUMBER(22,0) NOT NULL ,
PARENT_HIERARCHY_ID NUMBER(22,0),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
IS_ACTIVE VARCHAR2(1),
LIMS_HIERARCHY_CODE VARCHAR2(50),
MARKET_GLOBAL_INDUSTRY_ID NUMBER(22,0),
MARKET_GENARAL_INDUSTRY_ID NUMBER(22,0),
MARKET_INDUSTRY_SEGMENT_ID NUMBER(22,0),
CLIENT_MARKET_ID NUMBER(22,0),
TEMPLATE_ID NUMBER(22,0),
MXNS_ENTITY_ID NUMBER(22,0),
SOURCE_INSTANCE VARCHAR2(10),
CONSTRAINT PK_CUSTOMER_HIERARCHY PRIMARY KEY (CUSTOMER_ID,HIERARCHY_ID)
 );  
create table GDM_WEB.CUSTOMER_MEANING(
CUSTOMER_ID NUMBER(22,0) NOT NULL ,
SERVICE_CODE VARCHAR2(50) NOT NULL ,
MEANING_ID NUMBER(22,0),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL  );  
create table GDM_WEB.CUST_HIERARCHY_TRANS(
HIERARCHY_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
DESCRIPTION VARCHAR2(300),
CONSTRAINT PK_CUST_HIERARCHY_TRANS PRIMARY KEY (HIERARCHY_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.CUST_LIMS_SERVICE(
CUSTOMER_ID NUMBER(22,0) NOT NULL ,
SERVICE_ID NUMBER(22,0) NOT NULL ,
IS_ACTIVE VARCHAR2(1),
TEMPLATE_ID NUMBER(22,0),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(20),
HIERARCHY_ID NUMBER(22,0) NOT NULL ,
CONSTRAINT PK_CUST_LIMS_SERVICE PRIMARY KEY (CUSTOMER_ID,SERVICE_ID,HIERARCHY_ID)
 );  
create table GDM_WEB.ENTITY_MEANING(
ENTITY_ID NUMBER(22,0) NOT NULL ,
MEANING_ID NUMBER(22,0) NOT NULL ,
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
CONSTRAINT PK_ENTITY_MEANING PRIMARY KEY (ENTITY_ID,MEANING_ID)
 );  
create table GDM_WEB.FILE_TYPE(
FILE_TYPE_ID NUMBER(22,0) NOT NULL ,
FILE_DESC VARCHAR2(150),
FILE_MIME VARCHAR2(150),
FILE_EXTENSION VARCHAR2(30),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(20),
CONSTRAINT PK_FILE_TYPE PRIMARY KEY (FILE_TYPE_ID)
 );  
create table GDM_WEB.ITEM_CA(
AUDIT_ITEM_ID NUMBER(22,0) NOT NULL ,
CA_ID NUMBER(22,0) NOT NULL ,
ITEM_ISSUE_ID NUMBER(22,0),
CA_DESC VARCHAR2(1000),
CA_PRIORITY VARCHAR2(50),
CA_DEADLINE VARCHAR2(60),
CA_RESPONSIBLE VARCHAR2(300),
CA_DATE DATE
,
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
CONSTRAINT PK_ITEM_CA PRIMARY KEY (AUDIT_ITEM_ID,CA_ID)
 );  
create table GDM_WEB.ITEM_CATEGORY(
AUDIT_ITEM_ID NUMBER(22,0) NOT NULL ,
CATEGORY_ID NUMBER(22,0) NOT NULL ,
UPDATED_ON DATE
 NOT NULL ,
REFRESH_DATE DATE
,
CONSTRAINT PK_ITEM_CATEGORY PRIMARY KEY (AUDIT_ITEM_ID,CATEGORY_ID)
 );  
create table GDM_WEB.ITEM_FILE(
AUDIT_ITEM_ID NUMBER(22,0) NOT NULL ,
ORDER_NUMBER NUMBER(22,0) NOT NULL ,
FILE_TYPE_ID NUMBER(22,0),
FILE_CONTENT BLOB,
FILE_NAME VARCHAR2(100),
UPDATED_ON DATE
,
CONSTRAINT PK_ITEM_FILE PRIMARY KEY (AUDIT_ITEM_ID,ORDER_NUMBER)
 );  
create table GDM_WEB.ITEM_ISSUE(
AUDIT_ITEM_ID NUMBER(22,0) NOT NULL ,
ISSUE_ID NUMBER(22,0) NOT NULL ,
ISSUE_DESC VARCHAR2(1000),
UPDATED_BY VARCHAR2(10),
UPDATED_ON DATE
,
CONSTRAINT PK_ITEM_ISSUE PRIMARY KEY (AUDIT_ITEM_ID,ISSUE_ID)
 );  
create table GDM_WEB.ITEM_OPTION(
AUDIT_ITEM_ID NUMBER(22,0) NOT NULL ,
OPTION_ID NUMBER(22,0) NOT NULL ,
UPDATED_ON DATE
,
CONSTRAINT PK_ITEM_OPTION PRIMARY KEY (AUDIT_ITEM_ID,OPTION_ID)
 );  
create table GDM_WEB.ITEM_TRANS(
ITEM_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
ITEM_TITLE VARCHAR2(600),
CONSTRAINT PK_ITEM_TRANS PRIMARY KEY (ITEM_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.ITEM_VALUE(
AUDIT_ITEM_ID NUMBER(22,0) NOT NULL ,
AUDIT_ID NUMBER(22,0) NOT NULL ,
CHECKLIST_ITEM_ID NUMBER(22,0) NOT NULL ,
ITEM_ID NUMBER(22,0),
REPORTABLE_REFERENCE VARCHAR2(50),
IS_NE VARCHAR2(1),
IS_NA VARCHAR2(1),
RESULT VARCHAR2(300),
RESULT_TYPE NUMBER(22,0),
RESULT_COLOR VARCHAR2(20),
IS_BAD VARCHAR2(1),
SCORE NUMBER(22,0),
MAX_POINT NUMBER(22,0),
LEVEL_NUMBER NUMBER(22,0),
ORDER_NUMBER NUMBER(22,0),
ITEM_COMMENT VARCHAR2(1000),
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
UPDATED_ON DATE
,
CONSTRAINT PK_ITEM_VALUE PRIMARY KEY (AUDIT_ITEM_ID,AUDIT_ID,CHECKLIST_ITEM_ID)
 );  
create table GDM_WEB.ITEM_VALUE_TRANS(
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
AUDIT_ITEM_ID NUMBER(22,0) NOT NULL ,
TEXT_SHORT_RESULT VARCHAR2(20),
TEXT_LONG_RESULT VARCHAR2(20),
UPDATED_ON DATE
,
REFRESH_DATE DATE
,
CONSTRAINT PK_ITEM_VALUE_TRANS PRIMARY KEY (AUDIT_ITEM_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.LAB(
LAB_ID NUMBER(22,0) NOT NULL ,
LAB_DESC VARCHAR2(300),
SOURCE_INSTANCE VARCHAR2(10),
COUNTRY_CODE VARCHAR2(50),
TIME_ZONE VARCHAR2(10),
REMOVED VARCHAR2(1),
INTERNAL VARCHAR2(1),
IS_REPORTABLE VARCHAR2(1) DEFAULT 'F'
       ,
MXNS_ENTITY_ID NUMBER(22,0),
LIMS_LAB_CODE VARCHAR2(10),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
CONSTRAINT PK_LAB PRIMARY KEY (LAB_ID)
 );  
create table GDM_WEB.LAB_TYPE(
LAB_TYPE_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
LAB_TYPE_DESC VARCHAR2(50),
REMOVED VARCHAR2(1),
UPDATED_ON DATE
,
UPDATED_BY VARCHAR2(30),
CONSTRAINT PK_LAB_TYPE PRIMARY KEY (LAB_TYPE_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.LANGUAGE(
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_DESC VARCHAR2(50),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
IS_ACTIVE VARCHAR2(1) DEFAULT 'F',
WEB_LANGUAGE_CODE VARCHAR2(10),
CONSTRAINT PK_LANGUAGE PRIMARY KEY (LANGUAGE_ID)
 );  
create table GDM_WEB.LIST_ENTRY(
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
LIST_CODE VARCHAR2(20) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
ENTRY_NAME VARCHAR2(20) NOT NULL ,
ORDER_NO NUMBER(22,0),
ENTRY_VALUE VARCHAR2(1000),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_LIST_ENTRY PRIMARY KEY (SOURCE_INSTANCE,LIST_CODE,ENTRY_NAME,LANGUAGE_ID)
 );  
create table GDM_WEB.MARKET_CATEGORY(
MARKET_CATEGORY_ID NUMBER(22,0) NOT NULL ,
MARKET_CATEGORY_NAME VARCHAR2(60) NOT NULL ,
MARKET_CATEGORY_DESC VARCHAR2(300),
PARENT_MARKET_CATEGORY_ID NUMBER(22,0),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(30) NOT NULL  );  
create table GDM_WEB.MEANING(
MEANING_ID NUMBER(22,0) NOT NULL ,
DATA_TYPE VARCHAR2(20),
MEANING_GROUP VARCHAR2(20),
TARGET_TABLE VARCHAR2(30),
TARGET_FIELD VARCHAR2(30),
TARGET_SQL VARCHAR2(1000),
IS_ALWAYS_DISPLAYED VARCHAR2(1),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
IS_WEB_HIDDEN VARCHAR2(1) DEFAULT null
  );  
create table GDM_WEB.MEANING_TRANS(
MEANING_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
LABEL VARCHAR2(60),
CONSTRAINT PK_MEANING_TRANS PRIMARY KEY (MEANING_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.MXNS_ENTITY(
MXNS_ENTITY_ID NUMBER(22,0) NOT NULL ,
MXNS_ENTITY_LEGAL_DESC VARCHAR2(300) NOT NULL ,
MXNS_ENTITY_DESC VARCHAR2(300),
MXNS_CUST_SERVICE_ID NUMBER(22,0),
DEFAULT_DATE_FORMAT VARCHAR2(50),
DEFAULT_LANGUAGE_ID NUMBER(22,0),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
CONSTRAINT PK_MXNS_ENTITY PRIMARY KEY (MXNS_ENTITY_ID)
 );  
create table GDM_WEB.OPTIONS(
OPTION_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
OPTION_NAME VARCHAR2(150),
OPTION_DESC VARCHAR2(300),
OPTION_COMMENT VARCHAR2(300),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
CONSTRAINT PK_OPTIONS PRIMARY KEY (OPTION_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.PACKAGE(
PACKAGE_ID NUMBER(22,0) NOT NULL ,
SOURCE_INSTANCE VARCHAR2(10),
PACKAGE_TYPE VARCHAR2(50),
PACKAGE_CODE VARCHAR2(50),
IS_ACTIVE VARCHAR2(1),
IS_LAST_VERSION VARCHAR2(1),
MXNS_ENTITY_ID NUMBER(22,0),
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_PACKAGE PRIMARY KEY (PACKAGE_ID)
 );  
create table GDM_WEB.PACKAGE_ANALYSIS(
PACKAGE_ID NUMBER(22,0) NOT NULL ,
ANALYSIS_CODE VARCHAR2(10) NOT NULL ,
ANALYSIS_VARIATION VARCHAR2(10) NOT NULL ,
ORDER_NUMBER NUMBER(22,0) NOT NULL ,
METHOD_CODE VARCHAR2(50),
IS_REMOVABLE VARCHAR2(1),
UPDATED_ON DATE
,
IS_ACTIVE VARCHAR2(1),
CONSTRAINT PK_PACKAGE_ANALYSIS PRIMARY KEY (PACKAGE_ID,ANALYSIS_CODE,ANALYSIS_VARIATION,ORDER_NUMBER)
 );  
create table GDM_WEB.PACKAGE_ANALYSIS_TRANS(
PACKAGE_ID NUMBER(22,0) NOT NULL ,
ANALYSIS_ID NUMBER(22,0) NOT NULL ,
ORDER_NUMBER NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
PACK_ANA_LABEL VARCHAR2(50),
PACK_ANA_DESC VARCHAR2(300),
METHOD_DESC VARCHAR2(50),
CONSTRAINT PK_PACKAGE_ANALYSIS_TRANS PRIMARY KEY (PACKAGE_ID,ANALYSIS_ID,ORDER_NUMBER,LANGUAGE_ID)
 );  
create table GDM_WEB.PACKAGE_TRANS(
PACKAGE_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
PACKAGE_NAME VARCHAR2(300),
PACKAGE_DESC VARCHAR2(300),
PACKAGE_COMMENT VARCHAR2(300),
CONSTRAINT PK_PACKAGE_TRANS PRIMARY KEY (PACKAGE_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.PRODUCT(
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
PRODUCT_ID NUMBER(22,0) NOT NULL ,
SERVICE_ID NUMBER(22,0),
MXNS_ENTITY_ID NUMBER(22,0),
PRODUCT_CODE VARCHAR2(50),
PRODUCT_TYPE VARCHAR2(50),
IS_ACTIVE VARCHAR2(1),
IS_LAST_VERSION VARCHAR2(1),
UPDATED_ON DATE
 );  
create table GDM_WEB.PRODUCTS_PACKAGE(
PRODUCT_PACKAGE_ID NUMBER(22,0) NOT NULL ,
PRODUCT_ID NUMBER(22,0) NOT NULL ,
PACKAGE_ID NUMBER(22,0) NOT NULL ,
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_PRODUCTS_PACKAGE PRIMARY KEY (PRODUCT_PACKAGE_ID)
 );  
create table GDM_WEB.PRODUCT_TRANS(
PRODUCT_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
PRODUCT_LABEL VARCHAR2(300),
PRODUCT_COMMENT VARCHAR2(300),
CONSTRAINT PK_PRODUCT_TRANS PRIMARY KEY (PRODUCT_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.PROD_PACKAGE_FILTER(
PRODUCT_PACKAGE_ID NUMBER(22,0) NOT NULL ,
FILTER_NO NUMBER(22,0) NOT NULL ,
FILTER_CLAUSE VARCHAR2(300),
CONSTRAINT PK_PROD_PACKAGE_FILTER PRIMARY KEY (PRODUCT_PACKAGE_ID,FILTER_NO)
 );  
create table GDM_WEB.REPORT(
REPORT_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
REPORT_TYPE VARCHAR2(30) NOT NULL ,
SOURCE_REPORT_CODE VARCHAR2(50),
REPORT_PATH VARCHAR2(300),
GENERATED_DATE DATE
,
DELIVERED_DATE DATE
,
SUPERSEDED_BY VARCHAR2(100),
SOURCE_INSTANCE VARCHAR2(10),
UPDATED_ON DATE
 NOT NULL ,
FILE_TYPE_ID NUMBER(22,0) NOT NULL ,
CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_ID,LANGUAGE_ID,FILE_TYPE_ID,REPORT_TYPE)
 );  
create table GDM_WEB.RESULT(
RESULT_ID NUMBER(22,0) NOT NULL ,
SAMPLE_ID NUMBER(22,0) NOT NULL ,
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
LIMS_RESULT_NUM NUMBER(22,0) NOT NULL ,
LIMS_ANALYSIS_CODE VARCHAR2(50),
LIMS_ANALYSIS_VERSION VARCHAR2(50),
ANALYSIS_ID NUMBER(22,0),
LAB_TYPE_ID NUMBER(22,0),
CUST_ANALYSIS_CODE VARCHAR2(50),
STARTED_DATE DATE
,
REVIEWED_DATE DATE
,
EXPECTED_DATE DATE
,
TEST_LIST_CODE VARCHAR2(50),
METHOD VARCHAR2(50),
TESTING_LAB_ID NUMBER(22,0),
COA_ORDER_NUMBER NUMBER(22,0),
STATUS_ID NUMBER(22,0),
ACCREDITED VARCHAR2(1),
PRICE NUMBER(22,0),
CURRENCY_ID NUMBER(22,0),
RESULT VARCHAR2(300),
UNCERTAINTY VARCHAR2(300),
UNIT_ID NUMBER(22,0),
IN_ALERT VARCHAR2(1),
IN_SPEC VARCHAR2(1),
CUST_ALERT_CODE VARCHAR2(50),
MIN_LIMIT VARCHAR2(50),
MAX_LIMIT VARCHAR2(50),
IS_INVOICED VARCHAR2(1),
INVOICE_DATE DATE
,
WORST_CONCL_LEVEL_ID NUMBER(22,0),
RETEST VARCHAR2(1),
IS_REPORTABLE VARCHAR2(1),
PACKAGE_ID NUMBER(22,0),
REPORT_ID NUMBER(22,0),
AL_REPORT_ID NUMBER(22,0),
UPDATED_ON DATE
 NOT NULL ,
COA_NUMBER VARCHAR2(50),
CONSTRAINT PK_RESULT PRIMARY KEY (RESULT_ID)
 );  
create table GDM_WEB.RESULT_CONCL(
RESULT_CONCL_ID NUMBER(22,0) NOT NULL ,
RESULT_ID NUMBER(22,0) NOT NULL ,
CONCL_LEVEL_ID NUMBER(22,0) NOT NULL ,
CONCL_WGT_ID NUMBER(22,0),
TARGET_VALUE VARCHAR2(60),
LIMS_AXIS_CODE VARCHAR2(20) NOT NULL ,
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_RESULT_CONCL PRIMARY KEY (RESULT_CONCL_ID)
 );  
create table GDM_WEB.RESULT_CONCL_TRANS(
RESULT_CONCL_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
REF_VALUE VARCHAR2(60),
SHORT_LABEL VARCHAR2(20),
LONG_LABEL VARCHAR2(300),
SHORT_AXIS VARCHAR2(10),
LONG_AXIS VARCHAR2(300),
CONSTRAINT PK_RESULT_CONCL_TRANS PRIMARY KEY (RESULT_CONCL_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.RESULT_TRANS(
RESULT_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
TEST_NAME VARCHAR2(100),
RESULT_NAME VARCHAR2(100),
TEST_LIST_DESC VARCHAR2(300),
RESULT_NAME_INTERNAL VARCHAR2(100),
CONSTRAINT PK_RESULT_TRANS PRIMARY KEY (RESULT_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.SAMPLE(
SAMPLE_ID NUMBER(22,0) NOT NULL ,
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
LIMS_SAMPLE_NUM NUMBER(22,0) NOT NULL ,
SITE_ID NUMBER(22,0) NOT NULL ,
HIERARCHY_ID NUMBER(22,0),
CUSTOMER_ID NUMBER(22,0) NOT NULL ,
PROJECT_NAME VARCHAR2(50),
LIMS_SERVICE_CODE VARCHAR2(50),
LIMS_SERVICE_DESC VARCHAR2(300),
CATEGORY_ID NUMBER(22,0),
CUST_CATEGORY_CODE VARCHAR2(50),
SHIPVIA VARCHAR2(50),
PURCHASE_ORDER VARCHAR2(50),
LOGIN_DATE DATE
,
RECEIVED_DATE DATE
,
REVIEWED_DATE DATE
,
SAMPLED_DATE DATE
,
STARTED_DATE DATE
,
STATUS_ID NUMBER(22,0),
IN_ALERT VARCHAR2(1),
IN_SPEC VARCHAR2(1),
WORST_CONCL_LEVEL_ID NUMBER(22,0),
ACCREDITED VARCHAR2(1),
SOURCE_VISIT_NUM NUMBER(22,0),
LAB_ID NUMBER(22,0),
MXNS_ENTITY_ID NUMBER(22,0),
PRODUCT_ID NUMBER(22,0),
SERVICE_FAMILY_ID NUMBER(22,0),
SERVICE_ID NUMBER(22,0),
UPDATED_ON DATE
 NOT NULL ,
WEB_LOGIN_NUMBER NUMBER(22,0),
TEMPLATE_ID NUMBER(22,0),
CONSTRAINT PK_FACT_SAMPLES PRIMARY KEY (SOURCE_INSTANCE,LIMS_SAMPLE_NUM)
 );  
create table GDM_WEB.SAMPLE_CONCL(
SAMPLE_CONCL_ID NUMBER(22,0) NOT NULL ,
SAMPLE_ID NUMBER(22,0) NOT NULL ,
CONCL_LEVEL_ID NUMBER(22,0) NOT NULL ,
CONCL_WGT_ID NUMBER(22,0) NOT NULL ,
LIMS_AXIS_CODE VARCHAR2(20) NOT NULL ,
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_SAMPLE_CONCL PRIMARY KEY (SAMPLE_CONCL_ID)
 );  
create table GDM_WEB.SAMPLE_CONCL_TRANS(
SAMPLE_CONCL_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
SHORT_LABEL VARCHAR2(20),
LONG_LABEL VARCHAR2(300),
SHORT_AXIS VARCHAR2(10),
LONG_AXIS VARCHAR2(300),
AXIS_VARIATION VARCHAR2(100),
CONSTRAINT PK_SAMPLE_CONCL_TRANS PRIMARY KEY (SAMPLE_CONCL_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.SAMPLE_DETAIL(
SAMPLE_ID NUMBER(22,0) NOT NULL ,
MEANING_ID NUMBER(22,0) NOT NULL ,
VALUE VARCHAR2(1000),
VALUE_D DATE
,
VALUE_I NUMBER(22,0),
COA_ORDER_NUMBER NUMBER(22,0),
UPDATED_ON DATE
 NOT NULL ,
DATA_TYPE VARCHAR2(10),
CONSTRAINT PK_SAMPLE_DETAIL PRIMARY KEY (SAMPLE_ID,MEANING_ID)
 );  
create table GDM_WEB.SAMPLE_DETAIL_TRANS(
SAMPLE_ID NUMBER(22,0) NOT NULL ,
MEANING_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
LABEL VARCHAR2(60),
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_SAMPLE_DETAIL_TRANS PRIMARY KEY (SAMPLE_ID,MEANING_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.SERVICE(
SERVICE_ID NUMBER(22,0) NOT NULL ,
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
SERVICE_CODE VARCHAR2(50) NOT NULL ,
SERVICE_VERSION NUMBER(22,0) NOT NULL ,
IS_ACTIVE VARCHAR2(1),
IS_LAST_VERSION VARCHAR2(1),
MXNS_ENTITY_ID NUMBER(22,0),
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_SERVICE PRIMARY KEY (SOURCE_INSTANCE,SERVICE_CODE,SERVICE_VERSION)
 );  
create table GDM_WEB.SERVICE_TRANS(
SERVICE_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
SERVICE_DESC VARCHAR2(300),
CONSTRAINT PK_SERVICE_TRANS PRIMARY KEY (SERVICE_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.SITE(
SITE_ID NUMBER(22,0) NOT NULL ,
SITE_DESC VARCHAR2(300),
COUNTRY_CODE VARCHAR2(50),
ZIP VARCHAR2(50),
STREET_ADDR VARCHAR2(50),
ADDR_NR VARCHAR2(50),
CITY VARCHAR2(50),
STATE VARCHAR2(50),
LATITUDE NUMBER(22,0),
LONGITUDE NUMBER(22,0),
IS_ACTIVE VARCHAR2(1),
LIMS_SITE_CODE VARCHAR2(50),
SOURCE_INSTANCE VARCHAR2(10) NOT NULL ,
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
STREET_ADDR2 VARCHAR2(50),
CUST_SITE_CODE VARCHAR2(50),
SITE_PRODUCT_GROUP VARCHAR2(50),
SITE_REGION VARCHAR2(50),
CUST_SITE_CODE2 VARCHAR2(50),
MARKET_GLOBAL_INDUSTRY_ID NUMBER(22,0),
MARKET_GENARAL_INDUSTRY_ID NUMBER(22,0),
MARKET_INDUSTRY_SEGMENT_ID NUMBER(22,0),
CONSTRAINT PK_SITE PRIMARY KEY (SITE_ID)
 );  
create table GDM_WEB.SITE_HIERARCHY(
SITE_ID NUMBER(22,0) NOT NULL ,
HIERARCHY_ID NUMBER(22,0) NOT NULL ,
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
IS_ACTIVE VARCHAR2(1),
SH_ID NUMBER(22,0) NOT NULL ,
PREV_SH_ID NUMBER(22,0),
EFF_START_DATE DATE
,
EFF_END_DATE DATE
,
CONSTRAINT PK_SITE_HIERARCHY PRIMARY KEY (SH_ID)
 );  
create table GDM_WEB.STATUS(
STATUS_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
STATUS_DESC VARCHAR2(50),
SAMPLE_FILTER VARCHAR2(1),
AUDIT_FILTER VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(10) NOT NULL ,
CUSTOMER_STATUS_ID NUMBER(22,0),
CONSTRAINT PK_STATUS PRIMARY KEY (STATUS_ID,LANGUAGE_ID)
 );  
create table GDM_WEB.TEMPLATE(
TEMPLATE_ID NUMBER(22,0) NOT NULL ,
TEMPLATE_TYPE VARCHAR2(10),
SOURCE_INSTANCE VARCHAR2(10),
TEMPLATE_CODE VARCHAR2(10),
TEMPLATE_VERSION NUMBER(22,0) NOT NULL ,
TEMPLATE_DESC VARCHAR2(300),
IS_ACTIVE VARCHAR2(1),
UPDATED_ON DATE
,
CONSTRAINT PK_TEMPLATE PRIMARY KEY (TEMPLATE_ID)
 );  
create table GDM_WEB.TEMPLATE_FIELD(
TEMPLATE_ID NUMBER(22,0) NOT NULL ,
FIELD_NAME VARCHAR2(30) NOT NULL ,
ENTRY_MODE VARCHAR2(20),
ORDER_NUMBER NUMBER(22,0),
DEFAULT_VALUE VARCHAR2(300),
ALLOW_USER_ENTRY VARCHAR2(1),
DATA_TYPE VARCHAR2(10),
GROUP_NAME VARCHAR2(20),
MAX_LENGTH NUMBER(22,0),
MAX_LENGTH_TYPE VARCHAR2(5),
LIST_CODE VARCHAR2(20),
MEANING_ID NUMBER(22,0),
IS_REPORTABLE VARCHAR2(1),
IS_DOWNLOADABLE VARCHAR2(1),
IS_LOGIN_VISIBLE VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
CONSTRAINT PK_TEMPLATE_FIELD PRIMARY KEY (TEMPLATE_ID,FIELD_NAME)
 );  
create table GDM_WEB.TEMPLATE_FIELD_TRANS(
TEMPLATE_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
FIELD_NAME VARCHAR2(30) NOT NULL ,
FIELD_LABEL VARCHAR2(60),
CONSTRAINT PK_TEMPLATE_FIELD_TRANS PRIMARY KEY (TEMPLATE_ID,FIELD_NAME,LANGUAGE_ID)
 );  
create table GDM_WEB.UNIT_TRANS(
UNIT_ID NUMBER(22,0) NOT NULL ,
LANGUAGE_ID NUMBER(22,0) NOT NULL ,
UNIT_LABEL VARCHAR2(80),
UNIT_DESC VARCHAR2(1000),
UNIT_COMMENT VARCHAR2(300),
REMOVED VARCHAR2(1),
UPDATED_ON DATE
 NOT NULL ,
UPDATED_BY VARCHAR2(20) NOT NULL ,
CONSTRAINT PK_UNIT_TRANS PRIMARY KEY (UNIT_ID,LANGUAGE_ID)
 );  
   
 --- DROPPING AND CREATING SEQUENCES.  None yet. 
   
